<Project>
  <PropertyGroup>
    <SdkVersion>2022.1.1</SdkVersion>

    <Title>MemberOrderInspection</Title>
    <Description>MemberOrderInspection is a Resharper extension which inspects C# files against incorrect ordering of member declarations.</Description>

    <Authors>Onur "Xtro" Er</Authors>
  </PropertyGroup>
</Project>